main: me.oscar0713.EaseManage.Main
name: EaseManage
description: This plugin is for easy server management for server administrator.
version: 0.1.1
author: oscar0713
website: https://github.com/Oscar-0713/EaseManage
api-version: 1.18
commands:
  serverstatus:
    description: To check the current server status [TPS/Ping]
    permission: easemanage.serverstatus.use
  reload:
    description: To reload the whole server
    permission: easemanage.reload.use
  head:
    description: To get a player head
    permission: easemanage.head.use
  spawn:
    description: To teleport you to your spawnpoint (Bed)
    permission: easemanage.spawn.use
  stat:
    description: To check your in-game statistics
    permission: easemanage.stat.use
  backup:
    description: To backup the server to the disk
    permission: easemanage.backup.use

permissions:
  easemanage.admin.*:
    description: all permissions in this plugin
    default: op
    children:
      easemanage.head.use: true
      easemanage.reload.use: true
      easemanage.announce.use: true
      easemanage.backup.use: true
  easemanage.player.*:
    description: player default permission
    default: true
    children:
      easemanage.spawn.use: true
      easemanage.serverstatus.use: true
      easemanage.stat.use: true
    